javascripts:
  common:
    - app/javascripts/vendor/jquery.js
    - app/javascripts/vendor/jquery-ui.js    
    - app/javascripts/vendor/rails.js            
    - app/javascripts/vendor/mustache.js            
    - app/javascripts/vendor/jquery.mustache.js        
    - app/javascripts/vendor/*.js
    - app/javascripts/custom/*.js